"""Defines long strings used in discord communications with users."""

WIKIPEDIA_URL = (
    'https://en.wikipedia.org/wiki/The_Genius:_Rule_Breaker'
    '#Episode_2:_Seat_Exchange_(12_Contestants)')

RULES_STR = (
    'This game is based on a main match from the korean reality show '
    'The Genius.\n'
    'Rules for that version can be found at {url}.\n'
    "There's some minor differences in this implementation, but the idea is "
    "the same.\n"
    'Each player is imagined to be sitting in a circle, on seats numbered '
    'from 0.\n'
    'Each seat is adjacent to two other seats, wrapping around at the '
    'beginning and end.\n'
    'Every player is also assigned a secret number, from 0 up to the number '
    'of players-1.\n'
    'The game ends when a specific amount of players, depending on the total '
    'number of '
    'players, is seated such that their secret numbers are in increasing or '
    'decreasing '
    'order.\n'
    'The game only ends if there is *one* such streak, and it may not be '
    'longer '
    'than the specified length.\n'
    '\n'
    'At the start of the game, each player gains {start_garnets} garnets, '
    'which is the currency of the game.\n'
    'Players forming the winning streak are rewarded with {win_garnets} '
    'garnets by '
    'default.\n'
    '\n'
    'There is also one number assigned to be **X**, by default it starts as 0 '
    'and increases by one each round.\n'
    'The number that is X cannot be part of a streak, and you skip this '
    'number when '
    'calculating a streak.\n'
    'For example if X=3, 2 and 4 are considered adjacent and can form '
    'a streak.\n'
    'When the game ends, the player that holds the number currently '
    'assigned X loses '
    '{lose_garnets} garnets.\n'
    '\n'
    'At the beginning of each round the length of the longest streak '
    'is announced.\n'
    'This can be used to keep track of other players, or figure out '
    'their secret number.\n'
    '\n'
    'During each round players can propose to swap seats with another '
    'player, optionally '
    'bribing them with a few garnets as well.\n'
    'You can also donate garnets to other players, this is intended to be '
    'used for non-'
    'binding proposals.\n'
    'You can only swap seats once per round.\n'
    'By default all seat swaps are announced publicly, but this may be '
    'disabled.\n'
    'The ultimate objective of the game is to end the game with as many '
    'garnets as possible.\n'
    )
